"""add intro and text question support

Revision ID: eabff908f664
Revises: 6a22aaa8202a
Create Date: 2026-06-02 22:07:15.753771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabff908f664'
down_revision = '6a22aaa8202a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_intro', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('intro_text', sa.Text(), nullable=False, server_default='请认真阅读测评说明，客观、公正、独立完成本次民主测评。'))
        batch_op.add_column(sa.Column('intro_seconds', sa.Integer(), nullable=False, server_default='5'))

    with op.batch_alter_table('form_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.String(length=20), nullable=False, server_default='choice'))

    with op.batch_alter_table('survey_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_value', sa.Text(), nullable=False, server_default=''))
        batch_op.alter_column('option_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_answers', schema=None) as batch_op:
        batch_op.alter_column('option_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('text_value')

    with op.batch_alter_table('form_items', schema=None) as batch_op:
        batch_op.drop_column('item_type')

    with op.batch_alter_table('evaluation_forms', schema=None) as batch_op:
        batch_op.drop_column('intro_seconds')
        batch_op.drop_column('intro_text')
        batch_op.drop_column('show_intro')

    # ### end Alembic commands ###
